on:
  push:
    branches:
      - "main"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.0
        with:
          path: build
